### ISSUE TITLE
Age of Empires Online gr2 Models

### ISSUE THREAD

**Issue by Goldroger83** [kangcliff/Age-of-Empires-III#1]
Hi Man,

Im trying to import age of empires online gr2 models using grnreaderx but i faced few problems, i descovered that the version of granny2.dll used to export aoeo models is deffrent than aoe III (2.8.25) so i started modifing the cpp code and i succeed to import buildings and some units but still i have problem with bones and animations.
Can you help me on that  ? My Email: maghroum.hassen@gmail.com

**Comment by kangcliff** [comment]
Hello there, 

the internal data structures had been changed a lot since the version AoE III used, as well as the dll export functions. May I ask why are you trying to export models from AoEO before I start to investigate into your problem?

**Comment by Goldroger83** [comment]
Hi Man,
Im trying to use the AoEO models in RTS Game Prototype, by the way i fixed the problem and i changed the source the way to export the model with working animation.
I have found a new version of a granny sdk api reference document, based on that i fixed the program.
If you are interested about the program i can post the changes.
Thank you so much for replying to my query i really appreciate that.

**Comment by ellepereira** [comment]
@Goldroger83 still have that fix?
